[build] 
    command = "yarn build"
    functions = "functions"
    publish = "build"

# to access from [domain]/api/[filename]
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200