#    command = "yarn build"
#    publish = "build"
[build] 
    functions = "functions"

# to access from [domain]/api/[filename]
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200